---
abstract: extensions and convenience methods to manage background processes
author:
  - "Marty O'Brien <mob\\@cpan.org>"
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Forks-Super
no_index:
  directory:
    - t
    - inc
  package:
    - Sys::CpuAffinity
    - Signals::XSIG
    - Signals::XSIG::Default
recommends:
  DateTime::Format::Natural: 0.89
  JSON: 2.0
  Sys::CpuAffinity: 0.91
  Sys::CpuLoadX: 0.02
  Win32::API: 0.43
  Win32::Process: 0.11
  Win32::Process::Kill: 2.64
  YAML: 0.62
  YAML::Tiny: 1.39
requires:
  Test::More: 0
  Time::HiRes: 1.30
version: 0.57
