--- #YAML:1.0
name:                Forks-Super
version:             0.35
abstract:            extensions and convenience methods 
license:             perl
author:              
    - Marty O'Brien <mob@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
