--- #YAML:1.0
name:               Forks-Super
version:            0.51
abstract:           extensions and convenience methods to manage background processes.
author:
    - Marty O'Brien <mob\@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:   0
    Time::HiRes:  1.30
    Win32::API:   0.43
no_index:
    directory:
        - t
        - inc
    package:
        - Sys::CpuAffinity
        - Signals::XSIG
        - Signals::XSIG::Default
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    DateTime::Format::Natural:  0.89
    JSON:                 2.0
    Sys::CpuAffinity:     0.91
    Sys::CpuLoadX:        0.02
    Win32::API:           0.43
    Win32::Process:       0.11
    Win32::Process::Kill:  2.64
    YAML:                 0.62
    YAML::Tiny:           1.39
