--- #YAML:1.0
name:               Forks-Super
version:            0.32
abstract:           extensions and convenience methods 
author:
    - Marty O'Brien <mob@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    - Time::HiRes
    - 1.30
    - YAML
    - 0.62
    - JSON
    - 2.0
    - Sys::CpuAffinity
    - 0.9
    - Sys::CpuLoadX
    - 0.02
    - Win32::Process
    - 0.11
    - Win32::API
    - 0.43
